CREATE TABLE FUENTESSODA (
  CodFS INT,
  NombreFS VARCHAR(30),
  CONSTRAINT PK_CODFS PRIMARY KEY (CodFS)
);

CREATE TABLE BEBIDAS (
  CodBeb CHAR(4),
  NombreBeb VARCHAR(20),
  CONSTRAINT PK_CB PRIMARY KEY (CodBeb)
);

CREATE TABLE BEBEDOR (
  CI CHAR(10),
  Nombre VARCHAR(30),
  CONSTRAINT PK_BEBEDOR PRIMARY KEY (CI));

CREATE TABLE GUSTA (
  CiP CHAR(10),
  CodBebida CHAR(4),
  CONSTRAINT PK_GUSTA PRIMARY KEY (CiP,CodBebida),
  CONSTRAINT FK_CEDULA FOREIGN KEY (CiP) REFERENCES BEBEDOR (CI),
  CONSTRAINT FK_BEBIDA FOREIGN KEY (CodBebida) REFERENCES BEBIDAS (CodBeb));

CREATE TABLE FRECUENTA (
  CiPersona CHAR(10),
  CodigoFuente INT,
  CONSTRAINT PK_FRECUENTA PRIMARY KEY (CiPersona,CodigoFuente),
  CONSTRAINT FK_PERSONA FOREIGN KEY (CiPersona) REFERENCES BEBEDOR (CI),
  CONSTRAINT FK_FUENTE FOREIGN KEY (CodigoFuente) REFERENCES FUENTESSODA (CodFS));

CREATE TABLE VENDE (
  CodigoFS INT,
  CodigoBeb CHAR(4),
  Precio FLOAT(6),
  CONSTRAINT PK_VENDE PRIMARY KEY (CodigoFS,CodigoBeb),
  CONSTRAINT FK_FSODA FOREIGN KEY (CodigoFS) REFERENCES FUENTESSODA (CodFS),
  CONSTRAINT FK_BEB FOREIGN KEY (CodigoBeb) REFERENCES BEBIDAS (CodBeb));
  
