REM PREGUNTA 1
REM A

SELECT IDCINE
FROM CINE
MINUS
SELECT IDCINE
FROM FUNCION F JOIN PELICULA  P ON P.CENSURA='C' 
WHERE F.IDPELICULA=P.IDPELICULA;

REM B

SELECT IDCINE, AVG((BOLETOS_VENDIDOS/CAPACIDAD)*100) AVERAGE, MAX((BOLETOS_VENDIDOS/CAPACIDAD)*100) MAXIMUM, MIN((BOLETOS_VENDIDOS/CAPACIDAD)*100) MINIMUM
FROM FUNCION NATURAL JOIN SALA 
WHERE NUM_SALA=NUMERO
GROUP BY IDCINE;

REM C

SELECT IDCINE
FROM SE_ESTRENA
HAVING COUNT(*)>5
GROUP BY IDCINE;

REM D

SELECT DISTINCT C.IDCINE, NOMBRE
FROM (CINE C JOIN FUNCION F ON C.IDCINE=F.IDCINE) JOIN PELICULA P ON F.IDPELICULA=P.IDPELICULA
WHERE P.CATEGORIA='Accion' AND F.FECHA_HORA<SYSDATE
HAVING COUNT(*)>6
GROUP BY C.IDCINE, NOMBRE;

REM E

SELECT IDCINE
FROM SALA
HAVING MIN(CAPACIDAD)=AVG(CAPACIDAD)
GROUP BY IDCINE;

SELECT IDCINE
FROM SALA
WHERE NOT EXISTS ( SELECT  S1.NUMERO, S2.NUMERO
		   FROM SALA S1 JOIN SALA S2 ON S1.IDCINE=S2.IDCINE
		   WHERE  S1.NUMERO!=S2.NUMERO AND S1.CAPACIDAD!=S2.CAPACIDAD);


REM F

SELECT IDCINE, NUM_SALA, FECHA_HORA, F.IDPELICULA, TITULO, MONTO_RECABADO, BOLETOS_VENDIDOS
FROM FUNCION F JOIN PELICULA P ON F.IDPELICULA=P.IDPELICULA
WHERE MONTO_RECABADO>ALL(SELECT MONTO_RECABADO
			  FROM FUNCION F JOIN CINE C ON F.IDCINE=C.IDCINE
			  WHERE (ASCII(SUBSTR(LPAD(F.idcine,5,'0'),1,1)) =86) AND
				(ASCII(SUBSTR(LPAD(F.idcine,5,'0'),2,1)) =65) AND
				(ASCII(SUBSTR(LPAD(F.idcine,5,'0'),3,1)) =76) AND
				FECHA_HORA BETWEEN '01-JUL-02' AND '31-JUL-02'); 
