-- PREGUNTA 18

SELECT t1.CODBEB
FROM GUSTA t1
WHERE EXISTS (SELECT *
	      FROM GUSTA t2, BEBIDA t3
	      WHERE t3.NOMBREBEB='Malta' AND
	      t2.CODBEB=t3.CODBEB AND
	      t2.CI=t1.CI);

-- PREGUNTA 19

SELECT t1.CODFS
FROM FRECUENTA t1
WHERE EXISTS (SELECT *
	      FROM GUSTA t2, BEBIDA t3
	      WHERE t3.NOMBREBEB='Malta' AND
	      t3.CODBEB=t2.CODBEB AND t1.CI=t2.CI);

-- PREGUNTA 20

SELECT t1.CODFS
FROM FUENTESSODA t1
WHERE NOT EXISTS (SELECT *
		  FROM VENDE t2
		  WHERE t1.CODFS=t2.CODFS AND
		  NOT EXISTS (SELECT *
			      FROM FRECUENTA t3, BEBEDOR t4
			      WHERE t3.CI=t4.CI AND
			      t4.NOMBRE='Luis Perez' AND
			      NOT EXISTS (SELECT *
					  FROM VENDE t6
					  WHERE t6.CODFS = t3.CODFS AND
					  t6.CODBEB=t2.CODBEB)));


