ALTER TABLE INMUEBLE ADD CONSTRAINT DOM_SUP CHECK(superficie>0);
ALTER TABLE INMUEBLE ADD CONSTRAINT DOM_CANTU CHECK(cantUni>0);
ALTER TABLE INMUEBLE ADD CONSTRAINT DOM_ALICOM CHECK(0<=alicuotaCompone AND alicuotaCompone<=1);

ALTER TABLE UNIDAD ADD CONSTRAINT DOM_CIPOS CHECK(REGEXP_LIKE(ciPosee,'^[vVeE]-[[:digit:]]{8}$'));
ALTER TABLE UNIDAD ADD CONSTRAINT DOM_AREA CHECK(area>0);


ALTER TABLE PROVEEDOR ADD CONSTRAINT DOM_RIF CHECK(REGEXP_LIKE(rif,'^[gGnNjJ]-[[:digit:]]{8}$'));

ALTER TABLE GASTO ADD CONSTRAINT DOM_RIF CHECK(REGEXP_LIKE(rif,'^[gGnNjJ]-[[:digit:]]{8}$'));
ALTER TABLE GASTO ADD CONSTRAINT DOM_MONTO CHECK(monto>0);