SELECT NOMBREPROP, CEDULAPROP
FROM UNIDAD
WHERE UNIDAD.NUMERO=1 AND UNIDAD.IDINMUEBLE='ABCD';

SELECT DIRECCION,ALICUOTA
FROM UNIDAD, INMUEBLE
WHERE UNIDAD.IDINMUEBLE='ABCD' AND UNIDAD.NUMERO=1 AND UNIDAD.IDINMUEBLE=INMUEBLE.ID;

SELECT SUM(MONTO)
FROM UNIDAD, GASTO
WHERE UNIDAD.IDINMUEBLE='ABCD' AND UNIDAD.NUMERO=1 AND INCURRE_U_ID_INM='ABCD';

SELECT FECHA, CONCEPTO, MONTO
FROM UNIDAD, GASTO
WHERE UNIDAD.IDINMUEBLE='ABCD' AND UNIDAD.NUMERO=1 AND INCURRE_U_ID_INM='ABCD'
ORDER BY FECHA, CONCEPTO;

