SELECT DISTINCT NOMBREPROP, DIRECCION
FROM UNIDAD,INMUEBLE, CONDOMINIO
WHERE CONDOMINIO.FECHAPAGO IS NULL AND CONDOMINIO.IDINMUEBLE=INMUEBLE.ID;	

SELECT DISTINCT NOMBREPROP
FROM UNIDAD,INMUEBLE, CONDOMINIO
WHERE  CONDOMINIO.MONTO>=250000.00; 
