SPOOL gatac-domains.txt

ALTER TABLE CINE ADD (
  CONSTRAINT DOM_IDCINE
  CHECK ((ASCII(SUBSTR(LPAD(IdCine,5,'0'),1,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(IdCine,5,'0'),2,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(IdCine,5,'0'),3,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(IdCine,5,'0'),4,1)) BETWEEN 48 AND 57) AND
	 (ASCII(SUBSTR(LPAD(IdCine,5,'0'),5,1)) BETWEEN 48 AND 57)));



ALTER TABLE CINE ADD (
  CONSTRAINT DOM_PRECIO
   CHECK (Precio_entrada>0));

ALTER TABLE CINE ADD (
  CONSTRAINT DOM_NUMSALAS
  CHECK(num_salas BETWEEN 1 AND 99));

ALTER TABLE SALA ADD (
  CONSTRAINT DOM_IDCINESALA
  CHECK ((ASCII(SUBSTR(LPAD(idcine,5,'0'),1,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idcine,5,'0'),2,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idcine,5,'0'),3,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idcine,5,'0'),4,1)) BETWEEN 48 AND 57) AND
	 (ASCII(SUBSTR(LPAD(idcine,5,'0'),5,1)) BETWEEN 48 AND 57)));

ALTER TABLE SALA ADD (
  CONSTRAINT DOM_NUMERO
  CHECK(numero BETWEEN 1 AND 99));

ALTER TABLE SALA ADD (
  CONSTRAINT DOM_CAPACIDAD
  CHECK(capacidad>0));

ALTER TABLE PELICULA ADD (
  CONSTRAINT DOM_IDPELI
  CHECK ((ASCII(SUBSTR(LPAD(idpelicula,5,'0'),1,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),2,1)) BETWEEN 48 AND 57) AND
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),3,1)) BETWEEN 48 AND 57) AND
         (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),4,1)) BETWEEN 48 AND 57) AND
         (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),5,1)) BETWEEN 48 AND 57) AND         
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),6,1)) BETWEEN 48 AND 57)));



ALTER TABLE PELICULA ADD (
  CONSTRAINT DOM_CATEGORIA
  CHECK(categoria in('Comedia','Drama','Accion','Suspenso','Ciencia Ficcion','Romance','Documental','Terror','Musical','Animacion')));

ALTER TABLE PELICULA ADD (
  CONSTRAINT DOM_CENSURA
  CHECK(censura in('A','B','C','D')));

ALTER TABLE FUNCION ADD (
  CONSTRAINT DOM_IDCINEFUNC
  CHECK ((ASCII(SUBSTR(LPAD(id_cine,5,'0'),1,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(id_cine,5,'0'),2,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(id_cine,5,'0'),3,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(id_cine,5,'0'),4,1)) BETWEEN 48 AND 57) AND
	 (ASCII(SUBSTR(LPAD(id_cine,5,'0'),5,1)) BETWEEN 48 AND 57)));

ALTER TABLE FUNCION ADD (
  CONSTRAINT DOM_NUMEROSALA
  CHECK(numsala BETWEEN 1 AND 99));

ALTER TABLE FUNCION ADD (
  CONSTRAINT DOM_IDFUNC
  CHECK ((ASCII(SUBSTR(LPAD(idpelicula,5,'0'),1,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),2,1)) BETWEEN 48 AND 57) AND
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),3,1)) BETWEEN 48 AND 57) AND
         (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),4,1)) BETWEEN 48 AND 57) AND
         (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),5,1)) BETWEEN 48 AND 57) AND         
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),6,1)) BETWEEN 48 AND 57)));

ALTER TABLE FUNCION ADD (
  CONSTRAINT DOM_MONTO
  CHECK (montorecabado>=0));

ALTER TABLE FUNCION ADD (
  CONSTRAINT DOM_BOLVEN
  CHECK (boletos_vendidos>=0));

ALTER TABLE SE_ESTRENA ADD (
  CONSTRAINT DOM_IDCINEESTRENA
  CHECK ((ASCII(SUBSTR(LPAD(idcine,5,'0'),1,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idcine,5,'0'),2,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idcine,5,'0'),3,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idcine,5,'0'),4,1)) BETWEEN 48 AND 57) AND
	 (ASCII(SUBSTR(LPAD(idcine,5,'0'),5,1)) BETWEEN 48 AND 57)));

ALTER TABLE SE_ESTRENA ADD (
  CONSTRAINT DOM_IDPELIESTRENA
  CHECK ((ASCII(SUBSTR(LPAD(idpelicula,5,'0'),1,1)) BETWEEN 65 AND 90) AND
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),2,1)) BETWEEN 48 AND 57) AND
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),3,1)) BETWEEN 48 AND 57) AND
         (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),4,1)) BETWEEN 48 AND 57) AND
         (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),5,1)) BETWEEN 48 AND 57) AND         
	 (ASCII(SUBSTR(LPAD(idpelicula,5,'0'),6,1)) BETWEEN 48 AND 57)));



SPOOL OFF