REM PREG 5

CREATE VIEW CAPACIDADES AS (SELECT IDCINE, SUM(CAPACIDAD) S FROM SALA
GROUP BY IDCINE
HAVING SUM(CAPACIDAD)>580
);

REM UPDATE ES EL COMANDO QUE SE UTILIZA PARA MODIFICAR EL VALOR DE ATRIBUTO 
REM EN SQL. EN NUESTRO CASO PARTICULAR PARA AUMENTAR EL PRECIO DE LAS ENTRADAS EN LOS CINES QUE CUMPLAN LA CONSULTA DE ARRIBA.

UPDATE CINE SET PRECIO_ENTRADA=PRECIO_ENTRADA+(PRECIO_ENTRADA*.10) WHERE IDCINE IN (SELECT IDCINE FROM CAPACIDADES);




