REM PREGUNTA 3

REM OPCION 1

REM DELETE FROM FUNCION WHERE IDCINE=(SELECT IDCINE
REM				      FROM CINE
REM				      WHERE NOMBRE='Paraiso Cinex');

REM DELETE FROM SALA WHERE IDCINE =(SELECT IDCINE
REM				   FROM CINE
REM				WHERE NOMBRE='Paraiso Cinex');

REM DELETE FROM CINE WHERE IDCINE=(SELECT IDCINE
REM				FROM CINE
REM				WHERE NOMBRE='Paraiso Cinex');

REM OPCION 2


DELETE FROM CINE WHERE IDCINE=(SELECT IDCINE
				FROM CINE
				WHERE NOMBRE='Paraiso Cinex') ; 
CASCADE CONSTRAINTS;



