SPOOL PI-4.txt

DROP VIEW TRESMESES;
CREATE VIEW TRESMESES AS
SELECT NUMERO_HAB NRO, CODIGO_RES COD, NUM_AD NUMAD,NUM_NI NUMNI, FECHA_INGRESO FENTRADA, FECHA_EGRESO FSALIDA
FROM ASIGNA1 JOIN RESERVA1 ON CODIGO=CODIGO_RES
WHERE (FECHA_INGRESO BETWEEN SYSDATE - 90 AND SYSDATE) OR
      (FECHA_EGRESO BETWEEN SYSDATE - 90 AND SYSDATE) OR
      (FECHA_INGRESO< SYSDATE - 90 AND FECHA_EGRESO> SYSDATE);

REM PREG A
REM AQUI SE INTENTA DISMINUIR EN UN 20% LAS TARIFAS DE LAS HABITACIONES QUE NO HAN SIDO USADAS DURANTE MAS DE
REM TRES MESES. 

REM SE CREA LA VISTA CANTDIA PARA TENER EL NUMERO DE HABITACION, LA FECHA DE INGRESO Y LA FECHA DE EGRESO.
DROP VIEW CANTDIA;
CREATE VIEW CANTDIA AS
SELECT NUMERO_HAB H, FECHA_INGRESO FI, FECHA_EGRESO FE
FROM ASIGNA1 JOIN RESERVA1 ON CODIGO=CODIGO_RES
ORDER BY NUMERO_HAB;

REM ESTA VISTA SE CREA PARA HALLAR LA CANTIDAD DE DIAS TOTAL DE USO DE UNA HABITACION.
DROP VIEW CANTD;
CREATE VIEW CANTD AS
SELECT DISTINCT H H, SUM(FI-FE) SUMD FROM CANTDIA
GROUP BY H;

REM SE HACE EL UPDATE SOBRE HABITA1 DE LAS HABITACIONES ENCONTRADAS.
UPDATE HABITA1
    SET TARIFA=TARIFA*0.80
    WHERE NUMERO IN (
                     (SELECT H
                     FROM CANTD
                     WHERE SUMD<90)
                 UNION
                 ((SELECT NUMERO
                   FROM HABITA1
                   )
                   MINUS
                   (SELECT H
                   FROM CANTD)) 
                   );

REM PREG B

REM  LO QUE SE BUSCA ES AUMENTAR EN UN 15% LAS TARIFAS DE LAS HABITACIONES QUE HAN TENIDO MAS DIAS
REM DE OCUPACION DURANTE LOS ULTIMOS TRES MESES.

REM ESTA VISTA SE CREA PARA VER LA CANTIDAD DE DIAS TOTAL DE CADA HABITACION
DROP VIEW MAXDUR;
CREATE VIEW MAXDUR AS
SELECT DISTINCT NRO N, SUM(FSALIDA-FENTRADA) SUMD FROM TRESMESES
GROUP BY NRO;

REM ESTA VISTA SE HACE PARA HALLAR LA HABITACION CON LA MAXIMA CANTIDAD DE DIAS DE USO.
DROP VIEW MAXI;
CREATE VIEW MAXI AS
SELECT N FROM MAXDUR
WHERE SUMD >= ALL
                (SELECT SUMD 
                 FROM MAXDUR);

REM SE HACE EL UPDATE CON LA(S) HABITACION(ES) ENCONTRADAS EN LA VISTA ANTERIOR.
UPDATE HABITA1
    SET TARIFA=TARIFA*1.15
    WHERE NUMERO = (
                    SELECT N FROM MAXI);

REM 4c Disminuir en un 10% las tarifas de las habitaciones que han sido usadas en
REM    los últimostres meses pero con el menor número de ocupantes.

DROP VIEW MESES3;
CREATE VIEW MESES3 AS
  SELECT CODIGO, NUM_PERSONAS
  FROM RESERVA1
  WHERE (FECHA_INGRESO BETWEEN SYSDATE-90 AND SYSDATE) 
     OR (FECHA_EGRESO BETWEEN SYSDATE-90 AND SYSDATE) 
     OR (FECHA_INGRESO<SYSDATE-90 AND FECHA_EGRESO>SYSDATE);

UPDATE HABITA
     SET TARIFA = TARIFA*0.9
     WHERE NUMERO=ANY
          (SELECT DISTINCT NUMERO_HAB
               FROM MESES3 JOIN ASIGNA1 ON CODIGO_RES=CODIGO
               WHERE NUM_PERSONAS = (SELECT MIN(NUM_PERSONAS) FROM MESES3)
          );

REM D     
REM (d) Insertar la habitación B008 con la tarifa de la habitación A001

INSERT INTO HABITA1
     VALUES ('B008', (SELECT TARIFA 
                              FROM HABITA1 
                              WHERE(NUMERO='A001')
                         )
     )

SPOOL OFF

SPOOL PI-4.1.8.txt

SELECT * FROM HABITA1;

SPOOL OFF
