SPOOL PI-3.txt


REM A
REM Nombres de clientes en reserva que tienen consumos no pagados.



SELECT NOMBRE
 FROM RESERVA,CONSUMO
 WHERE CODIGO=CODIGO_RES AND TIPO_PAGO IS NULL;

REM B
REM Nombres de los clientes que no tienen consumos no pagados.

SELECT NOMBRE
 FROM RESERVA,CONSUMO
 WHERE CODIGO=CODIGO_RES
MINUS
SELECT NOMBRE
 FROM RESERVA,CONSUMO
 WHERE CODIGO=CODIGO_RES AND TIPO_PAGO IS NULL;

REM C
REM Monto total, mínimo, máximo y promedio de todos los consumos efectuados 
REM por cada nombre de servicio.


SELECT NOMBRE,MAX(MONTO),MIN(MONTO),AVG(MONTO),SUM(MONTO)
 FROM SERVICIO,CONSUMO
 WHERE ID_SERVICIO=ID
 GROUP BY NOMBRE;

REM D
REM Consumo con el monto máximo sin utilizar la función de agregación MAX

SELECT NUM_FACTURA,MONTO
 FROM CONSUMO
 WHERE MONTO >= ALL ( SELECT MONTO
		    FROM CONSUMO);

REM E
REM Cédula de los clientes, código y monto total consumido de las
REM reservaciones que tienen consumo total por encima de un monto dado.

SELECT CEDULA,CODIGO,SUM(MONTO)
 FROM RESERVA JOIN CONSUMO ON CODIGO=CODIGO_RES
 GROUP BY CEDULA,CODIGO
 HAVING SUM(MONTO)>&MONTOMINIMO;

REM F
REM Habitaciones que no fueron utilizadas durante los últimos quince días.

SELECT NUMERO
	FROM HABITA
MINUS
SELECT NUMERO_HAB
	FROM RESERVA JOIN ASIGNA ON CODIGO=CODIGO_RES
	WHERE (FECHA_INGRESO BETWEEN SYSDATE-15 AND SYSDATE) 
	OR (FECHA_EGRESO BETWEEN SYSDATE-15 AND SYSDATE)
	OR (FECHA_INGRESO<SYSDATE-15 AND FECHA_EGRESO>SYSDATE);

REM G
REM Habitaciones que han tenido el mayor monto total de consumos.

DROP VIEW SUMCONSUMOHAB;
CREATE VIEW SUMCONSUMOHAB AS
	SELECT NUMERO_HAB,SUM(MONTO) SUMA
 		FROM RESERVA JOIN CONSUMO ON CODIGO=CODIGO_RES
 		GROUP BY NUMERO_HAB;

SELECT NUMERO_HAB
 FROM SUMCONSUMOHAB
 WHERE SUMA = (SELECT MAX(SUMA)
								FROM SUMCONSUMOHAB);

REM H
REM Identificación de los servicios que han sido usados por huéspedes de habitaciones
REM con la tarifa más baja y que pertenecen a reservaciones con niños.

DROP VIEW RTMBCNINOS;
CREATE VIEW RTMBCNINOS AS
	SELECT NUMERO_HAB NHAB,CODIGO_RES CRES
	FROM HABITA JOIN ASIGNA ON NUMERO_HAB=NUMERO
	WHERE TARIFA = (SELECT MIN(TARIFA)
								  	FROM HABITA)
		AND NUM_NI > 0;

SELECT DISTINCT ID_SERVICIO
	FROM CONSUMO,RTMBCNINOS
	WHERE NUMERO_HAB=NHAB AND CODIGO_RES=CRES;

REM I
REM Consumos efectuados en el servicio que tiene el promedio más alto en montos de
REM consumos.

DROP VIEW PROMPORCONSUM;
CREATE VIEW PROMPORCONSUM AS
	SELECT ID_SERVICIO,AVG(MONTO) PROM
 		FROM CONSUMO
 		GROUP BY ID_SERVICIO;

SELECT *
	FROM CONSUMO
	WHERE ID_SERVICIO = (SELECT ID_SERVICIO
												FROM PROMPORCONSUM
												WHERE PROM=(SELECT MAX(PROM)
																			FROM PROMPORCONSUM
																	 )
											);

REM J
REM Reservas donde los clientes han consumido todos los servicios.

DROP VIEW CODSTODSER;
CREATE VIEW CODSTODSER AS
	SELECT CODIGO COD
		FROM RESERVA
	MINUS
	SELECT DISTINCT CODIGO
		FROM(SELECT CODIGO, ID
				 	 FROM RESERVA CROSS JOIN SERVICIO
				 MINUS 
				 SELECT CODIGO_RES, ID_SERVICIO 
					 FROM CONSUMO
			   );

	SELECT *
		FROM RESERVA JOIN CODSTODSER 
										ON CODIGO=COD;

SPOOL OFF
