REM 4c Disminuir en un 10% las tarifas de las habitaciones que han sido usadas en
REM    los últimostres meses pero con el menor número de ocupantes.

DROP VIEW MESES3;
CREATE VIEW MESES3 AS
  SELECT CODIGO, NUM_PERSONAS
  FROM RESERVA
  WHERE (FECHA_INGRESO BETWEEN SYSDATE-90 AND SYSDATE) 
	OR (FECHA_EGRESO BETWEEN SYSDATE-90 AND SYSDATE) 
	OR (FECHA_INGRESO<SYSDATE-90 AND FECHA_EGRESO>SYSDATE);

UPDATE HABITA
	SET TARIFA = TARIFA*0.9
	WHERE NUMERO=ANY
		(SELECT DISTINCT NUMERO_HAB
			FROM MESES3 JOIN ASIGNA ON CODIGO_RES=CODIGO
			WHERE NUM_PERSONAS = (SELECT MIN(NUM_PERSONAS) FROM MESES3)
		);
