CREATE VIEW SOL AS
SELECT *
FROM
(SELECT CODIGO, FECHA_INGRESO, FECHA_EGRESO
FROM
RESERVA
WHERE ((FECHA_INGRESO BETWEEN SYSDATE-90 AND SYSDATE) OR (FECHA_EGRESO BETWEEN SYSDATE-90 AND SYSDATE)) 
OR    ((FECHA_INGRESO<SYSDATE-90) AND (FECHA_EGRESO>SYSDATE)))
JOIN
ASIGNA
ON(CODIGO=CODIGO_RES)
;
