SPOOL Pregunta4.txt

DROP VIEW TRESMESES;
CREATE VIEW TRESMESES AS
SELECT NUMERO_HAB NRO, CODIGO_RES COD, NUM_AD NUMAD,NUM_NI NUMNI, FECHA_INGRESO FENTRADA, FECHA_EGRESO FSALIDA
FROM ASIGNA1 JOIN RESERVA1 ON CODIGO=CODIGO_RES
WHERE (FECHA_INGRESO BETWEEN SYSDATE - 90 AND SYSDATE) OR
      (FECHA_EGRESO BETWEEN SYSDATE - 90 AND SYSDATE) OR
      (FECHA_INGRESO< SYSDATE - 90 AND FECHA_EGRESO> SYSDATE);

REM PREG A

DROP VIEW CANTDIA;
CREATE VIEW CANTDIA AS
SELECT NUMERO_HAB H, FECHA_INGRESO FI, FECHA_EGRESO FE
FROM ASIGNA1 JOIN RESERVA1 ON CODIGO=CODIGO_RES
ORDER BY NUMERO_HAB;

DROP VIEW CANTD;
CREATE VIEW CANTD AS
SELECT DISTINCT H H, SUM(FI-FE) SUMD FROM CANTDIA
GROUP BY H;

UPDATE HABITA1
    SET TARIFA=TARIFA*0.80
    WHERE NUMERO IN (
                     (SELECT H
                     FROM CANTD
                     WHERE SUMD<90)
                 UNION
                 ((SELECT NUMERO
                   FROM HABITA1
                   )
                   MINUS
                   (SELECT H
                   FROM CANTD)) 
                   );

REM PREG B

DROP VIEW MAXDUR;
CREATE VIEW MAXDUR AS
SELECT DISTINCT NRO N, SUM(FSALIDA-FENTRADA) SUMD FROM TRESMESES
GROUP BY NRO;

DROP VIEW MAXI;
CREATE VIEW MAXI AS
SELECT N FROM MAXDUR
WHERE SUMD >= ALL
                (SELECT SUMD 
                 FROM MAXDUR);


UPDATE HABITA1
    SET TARIFA=TARIFA*1.15
    WHERE NUMERO = (
                    SELECT N FROM MAXI);



SPOOL OFF